title: "Exploring Libraries/Archives"
author: "Fiercefire"
email: "12orbmine@gmail.com"


theme: minima

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: "https://fiercefire.github.io/Library-Website"
      type: post
    values:
      tags: Other

home_post_limit: 7

timezone: America/Los_Angeles
